services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-mooviai-homolog
    restart: unless-stopped
    ports:
      - "30500:5432"
    environment:
      - POSTGRES_USER=mooviai
      - POSTGRES_PASSWORD=ServerMoovia123
      - POSTGRES_DB=cinemas
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - pgdata-vector-homolog:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=cinemas
      -c timezone='America/Sao_Paulo'
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

volumes:
  pgdata-vector-homolog:
